apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: {{ $.Release.Namespace }}
  labels:
    app: guacd
spec:
  ports:
    - name: guacd
      port: 4822
      targetPort: 4822
      protocol: TCP
  selector:
    app: guacd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
        - name: guacd
          image: guacamole/guacd:1.5.5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4822
          readinessProbe:
            tcpSocket:
              port: 4822
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 4822
            initialDelaySeconds: 15
            periodSeconds: 20
