{{- if .Values.scripts }}
{{- with .Values.scripts.cloudInit }}
{{- if or .userData .networkData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lab-virtualmachine.cloud-init-secret" $ }}
  labels:
    {{- include "lab-virtualmachine.labels" $ | nindent 4 }}
data:
{{- if .userData }}
  userdata: |-
{{- .userData | b64enc | nindent 4 }}
{{- end }}
{{- if .networkData }}
  networkdata: |-
{{- .networkData | b64enc | nindent 4 }}
{{- end }}

{{- end }}
{{- end }}
{{- end }}
