{{- if $.Values.source }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Release.Name }}
  namespace: {{ $.Values.source.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ $.Release.Namespace }}
{{- end }}
