name: publish-charts
on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '!**/*.md'
  workflow_dispatch:

jobs:
  publish-charts:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Get 'KubeVirt VM' Helm chart version
        id: kubevirt-vm-chart-version
        env:
          CHART_PATH: charts/kubevirt-vm
        run: |
          CHART_VERSION=$(helm show chart $CHART_PATH | grep -E "^version:" | awk '{print $2}')
          echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT

      - name: Get 'KubeVirt DVs' Helm chart version
        id: kubevirt-dvs-chart-version
        env:
          CHART_PATH: charts/kubevirt-dvs
        run: |
          CHART_VERSION=$(helm show chart $CHART_PATH | grep -E "^version:" | awk '{print $2}')
          echo "version=$CHART_VERSION" >> $GITHUB_OUTPUT

      - name: Publish 'KubeVirt VM' Helm chart
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: kubevirt-vm
          repository: chomatdam/charts
          tag: ${{ steps.kubevirt-vm-chart-version.outputs.version }}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.github_token }}
          update_dependencies: 'true'

      - name: Publish 'KubeVirt DVs' Helm chart
        uses: appany/helm-oci-chart-releaser@v0.4.2
        with:
          name: kubevirt-dvs
          repository: chomatdam/charts
          tag: ${{ steps.kubevirt-dvs-chart-version.outputs.version }}
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.github_token }}
          update_dependencies: 'true'
